# Generated by Django 4.2.5 on 2023-09-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('banyak', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('harga', models.IntegerField()),
                ('jenis', models.CharField(max_length=100)),
            ],
        ),
    ]
